server:
    port: 80
spring:
    datasource:
        url: jdbc:mysql://192.168.0.146:3307/test
        username: root
        password: offen
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 5
        minIdle: 5
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss

    redis:
      database: 1
      host: 123.56.95.42
      port: 6379
#      password: redis
      maxActive: 7           #可用连接实例的最大数目，默认值为8
      maxWait: 15000         #最大的等待时间，如果超过等待时间，则直接抛出JedisConnectionException
      maxIdle: 7             # 连接池中的最大空闲连接
      minIdle: 0             # 连接池中的最小空闲连接
      timeout: 3000                 #连接超时时间（毫秒）

#---------mybatis配置---------------
mybatis:
   typeAliasesPackage: com.offenhealth.hdmp.code.model       #实体扫描
   mapper-locations: classpath:mapper/*.xml
#分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#------beetl设置----------
beetl:
    pagePath: /templates                #模板文件位置
    properties: classpath:/beetl.properties     #beetl属性文件


